"""Super Signals API package.

Explicit present-tense provider protection/exit instructions are production safety
policy, not test helpers. Install deterministic policy overrides as soon as the
application package is imported so the live listener, V1 policy and regression tests
all run the same broker-facing rules.
"""

from app.literal_management_overrides import install_literal_management_overrides
from app.plain_range_order_type_override import install_plain_range_order_type_override

install_literal_management_overrides()
install_plain_range_order_type_override()

from app.deterministic_first_ai import install_deterministic_first_ai

install_deterministic_first_ai()

from app.market_at_best_price_override import install_market_at_best_price_override

install_market_at_best_price_override()

from app.bare_gold_now_override import install_bare_gold_now_override

install_bare_gold_now_override()

from app.bare_gold_now_loader_fix import install_bare_gold_now_loader_fix

install_bare_gold_now_loader_fix()

from app.preserve_broker_protection_override import install_preserve_broker_protection_override

install_preserve_broker_protection_override()

from app.breakeven_tp_repair import install_breakeven_tp_repair

install_breakeven_tp_repair()

from app.paper_live_entry_guard import install_paper_live_entry_guard

install_paper_live_entry_guard()

from app.paper_market_execution_policy import install_paper_market_execution_policy

install_paper_market_execution_policy()

from app.provider_entry_reliability_overrides import install_provider_entry_reliability_overrides

install_provider_entry_reliability_overrides()

from app.tgc_entry_dialect_override import install_tgc_entry_dialect_override

install_tgc_entry_dialect_override()

from app.tgc_source_profile_override import install_tgc_source_profile_override

install_tgc_source_profile_override()

from app.add_market_lifecycle_override import install_add_market_lifecycle_override

install_add_market_lifecycle_override()

from app.execution_path_reliability_overrides import install_execution_path_reliability_overrides

install_execution_path_reliability_overrides()

from app.paper_margin_capacity_override import install_paper_margin_capacity_override

install_paper_margin_capacity_override()

from app.pending_reconciliation_parity_override import (
    install_pending_reconciliation_parity_override,
)

install_pending_reconciliation_parity_override()

from app.telegram_revision_serialization import install_telegram_revision_serialization

install_telegram_revision_serialization()

from app.telegram_fast_ingress import install_telegram_fast_ingress

install_telegram_fast_ingress()

from app.performance_account_truth_override import install_performance_account_truth_override

install_performance_account_truth_override()

from app.account_truth_poll_override import install_account_truth_poll_override

install_account_truth_poll_override()

from app.ambiguous_trade_reconciliation_override import (
    install_ambiguous_trade_reconciliation_override,
)

install_ambiguous_trade_reconciliation_override()

from app.aug18_trade_capture_overrides import install_aug18_trade_capture_overrides

install_aug18_trade_capture_overrides()
